---

- hosts: fotobox
  user: root

  vars:
    
    user: fotobox

    getty_service: /lib/systemd/system/getty@.service
    autologin: autologin
    autologin_service: "/etc/systemd/system/{{ autologin }}@.service"
    tty: tty1

    scripts_dir: "~{{ user }}/bin"

    fluxbox_autostart:
      - xterm -geometry 168x55+0+0 -maximized -e bin/dropbox.sh

    software:
      - ca-certificates
      - network-manager
      - net-tools
      - wireless-tools
      - wpagui
      - curl
      - git
      - python-gpgme
      - xserver-xorg-core
      - xserver-xorg
      - xinit
      - xterm
      - fluxbox
      - gphoto2
      - feh
      - qrencode
      - libxslt1.1

    dropbox: https://www.dropbox.com/download?dl=packages/ubuntu/dropbox_2015.10.28_amd64.deb

  handlers:

    - name: restart tty
      systemd:
        name: "{{ autologin }}@{{ tty }}"
        state: restarted

  tasks:

    - name: check for correct host os
      assert:
        that: "{{ item }}"
      with_items:
        - "ansible_distribution == 'Debian'"
        - "ansible_distribution_major_version == '9'"

    - name: user account created
      user:
        name: "{{ user }}"
        comment: photobooth autologin
        shell: /bin/bash
        state: present
      notify: restart tty

    - name: getty service definition copied
      copy:
        force: no
        remote_src: yes
        src: "{{ getty_service }}"
        dest: "{{ autologin_service }}"

    - name: autologin service's execstart configured
      lineinfile:
        path: "{{ autologin_service }}"
        regexp: "^ExecStart="
        line: "ExecStart=-/sbin/agetty --autologin {{ user }} --noclear %I $TERM"

    - name: original getty disabled
      systemd:
        name: "getty@{{ tty }}"
        state: stopped
        enabled: no

    - name: autologin enabled
      systemd:
        name: "{{ autologin }}@{{ tty }}"
        state: started
        enabled: yes

    - name: software is installed
      apt:
        name: "{{ software }}"
        state: present
        update_cache: yes
        install_recommends: no
      notify: restart tty

    - name: dropbox cli installed
      apt:
        deb: "{{ dropbox }}"
        state: present

    - name: dropbox dist installed
      become: yes
      become_user: "{{ user }}"
      become_method: su
      shell: echo y | dropbox start -i
      args:
        creates: "~{{ user }}/.dropbox-dist/dropboxd"

    - name: configured startx default for user
      copy:
        src: conf/bash_profile
        dest: "~{{ user }}/.bash_profile"
        owner: "{{ user }}"
      notify: restart tty

    - name: fluxbox config directory exists
      file:
        state: directory
        path: "~{{ user }}/.fluxbox"
        owner: "{{ user }}"

    - name: configured fluxbox startup scripts
      template:
        src: conf/fluxbox_startup.j2
        dest: "~{{ user }}/.fluxbox/startup"
        owner: "{{ user }}"
        backup: yes
      notify: restart tty

    - name: scripts directory created
      file:
        state: directory
        path: "{{ scripts_dir }}"
        owner: "{{ user }}"
      notify: restart tty

    - name: copied scripts
      copy:
        src: "{{ item }}"
        dest: "{{ scripts_dir }}/"
        owner: "{{ user }}"
        mode: 0755
      with_fileglob:
        - "scripts/*.sh"
      notify: restart tty

    - name: debug | always restart tty
      command: /bin/true
      notify: restart tty
