---

- hosts: fotobox
  vars:

    # autologin user to start desktop and capture
    user: fotobox

    # start applications automatically
    fluxbox_autostart:
      - xset -dpms s off # disable screen blank
      - wicd-client -t & # start network config tray
      - unclutter -idle 5 -root &
      #- xterm -geometry 168x55+0+0 -maximized &

    # add entries to right-click menu on desktop
    fluxbox_menu:
      - { name: Terminal, cmd: x-terminal-emulator }
      - { name: Photobooth, cmd: photobooth.sh }
      - { name: Network Config, cmd: wicd-client --no-tray }
      - { name: File Explorer, cmd: thunar }
      - { name: Web Browser, cmd: x-www-browser }

    # install required software
    software:
      # curl is useful
      - ca-certificates
      - curl
      # display manager
      - xserver-xorg
      - xinit
      - x11-xserver-utils
      - xterm
      - fluxbox
      - unclutter
      # network setup tools
      - net-tools
      - wireless-tools
      - wicd
      # required or useful desktop applications
      - gphoto2
      - feh
      - thunar
      - firefox-esr

    # disable these monitors because they interfere with our udev rule
    gvfs_monitors:
      - gvfs-gphoto2-volume-monitor
      - gvfs-mtp-volume-monitor
      - gvfs-udisks2-volume-monitor

    # trigger udev rule for these vendor ids
    camera_vendors:
      - 04a9 #Canon

  handlers:

    # restart the desktop if config changes occurred
    - name: restart tty
      systemd:
        name: getty@*
        state: restarted

  tasks:

    - name: check for expected linux distribution
      assert:
        that: "{{ item }}"
      with_items:
        - "ansible_distribution == 'Debian'"
        - "ansible_distribution_major_version == '9'"
      tags: [ check ]

    - name: reduce grub timeout
      lineinfile:
        path: /etc/default/grub
        regexp: '^GRUB_TIMEOUT='
        line: GRUB_TIMEOUT=1
      register: grub_defaults
      tags: [ grub, conf ]

    - name: update grub configuration
      command: update-grub
      when: grub_defaults is changed
      tags: [ grub, conf ]

    - name: user account created
      user:
        name: "{{ user }}"
        comment: photobooth autologin
        shell: /bin/bash
        state: present
      notify: restart tty
      tags: [ conf ]

    - name: getty override directory exists
      file:
        state: directory
        path: /etc/systemd/system/getty@.service.d
      tags: [ getty, conf ]

    - name: getty autologin override in place
      copy:
        dest: /etc/systemd/system/getty@.service.d/autologin.conf
        content: |
          [Service]
          ExecStart=
          ExecStart=-/sbin/agetty --autologin {{ user }} --noclear %I $TERM
      notify: restart tty
      tags: [ getty, conf ]

    - name: required software is installed
      apt:
        name: "{{ software }}"
        state: present
        update_cache: no
        install_recommends: no
      ignore_errors: yes
      register: apt_install
      notify: restart tty
      tags: [ software ]

    - name: retry installing software with updated cache
      apt:
        name: "{{ software }}"
        state: present
        update_cache: yes
        install_recommends: no
      when: apt_install is failed
      notify: restart tty
      tags: [ software ]

    - name: configured startx default for user
      copy:
        dest: "~{{ user }}/.bash_profile"
        owner: "{{ user }}"
        content: |
          # automatically start display server upon autologin on tty1
          if [[ -z $DISPLAY ]] && [[ $(tty) = /dev/tty1 ]]; then
            exec startx
          fi
      notify: restart tty
      tags: [ desktop, conf ]

    - name: fluxbox configuration directory exists
      file:
        state: directory
        path: "~{{ user }}/.fluxbox"
        owner: "{{ user }}"
        group: "{{ user }}"
      tags: [ desktop, conf ]

    - name: fluxbox configuration applied
      template:
        src: "{{ item }}"
        dest: "~{{ user }}/.fluxbox/{{ item | basename | regex_replace('\\.j2','') }}"
        owner: "{{ user }}"
        group: "{{ user }}"
        backup: yes
      with_fileglob:
        - ../fluxbox/*.j2
      notify: restart tty
      tags: [ desktop, conf ]

    - name: copied photobooth files
      copy:
        src: "{{ item.src }}"
        dest: "/usr/local/{{ item.dest }}"
        mode: "{{ item.mode | default(0644) }}"
      with_items:
        - { src: ../photobooth.sh, dest: bin/photobooth.sh, mode: "0755" }
        - { src: ../start.png, dest: share/photobooth_start.png }
      notify: restart tty
      tags: [ script ]

    - name: inserted udev rule to start photobooth
      copy:
        dest: /etc/udev/rules.d/10-photobooth.rules
        content: |
          {% for item in camera_vendors -%}
          SUBSYSTEM=="usb", DRIVERS=="usb", ACTION=="add", ATTRS{idVendor}=="{{ item }}", RUN+="/bin/su {{ user }} -c /usr/local/bin/photobooth.sh"
          {% endfor %}
      tags: [ udev, conf ]

    - name: disabled gvfs monitors if installed
      systemd:
        name: "{{ item }}"
        state: stopped
        enabled: no
      with_items: "{{ gvfs_monitors }}"
      ignore_errors: yes
      tags: [ gvfs, udev, conf ]